Feed-B/frontend

- app/_constants/StackData.ts
- app/main/_components/SideBar/SideBar.tsx
FULL_STACK_DATA 변수를  SideBar.tsx -> StackData.ts로 옮김
- #8
없음
> [Byeonghyeon] FULL_STACK_DATA 위치 변경

- app/_components/Header/DropDownBox.tsx
- app/_components/Header/Header.tsx
- app/_components/Profile/Profile.tsx
- app/main/_components/SearchBar/SearchBar.tsx
- app/main/_components/SelectStack/SelectStack.tsx
- app/main/_components/SideBar/StackItem.tsx
- app/main/_components/SideBar/StackList.tsx
- app/main/_components/SortFilter/SortFilter.tsx
- app/main/_components/StackBox/StackBox.tsx
- app/main/layout.tsx
- 레이아웃 함수명 변경
- iamge 태그 경고 해결
- 필요없는 flex-row 스타일 제거
- 버튼과 로고에 링크 연결
- #19
> [Byeonghyeon] 메인 페이지 코드 컨벤션 설정 및 성능 개선

- app/_components/Modal/Modal.tsx
- app/_hooks/useHandleModalClick.ts
- app/_hooks/useModal.ts
- app/_utils/ModalPortal.ts
- app/layout.tsx
- app/signup/_components/ExampleButton/ExampleButton.tsx
- app/signup/_components/ExampleModal/ExampleModal.tsx
- app/signup/_components/FirstStep/FirstStep.tsx
- package-lock.json
- package.json
- tailwind.config.ts
사용방법을 위해서 ExampleButton하고 ExampleModal 만들어놨습니다.
- https://github.com/Feed-B/frontend/issues/11
> [Seunghoon] 공통컴포넌트[모달] 구현

- app/_components/Modal/Modal.tsx
- app/_hooks/useHandleModalClick.ts
- app/_utils/ModalPortal.ts
* 코드리뷰 리팩토링
코드리뷰 달아주신거 수정하고 바로 푸쉬해야되는데 실수로 rebas e하고나서 푸쉬하려하니까 오류떠서 원래 있던 pr은 merge하고 새로 pr올립니다 ㅠ
- https://github.com/Feed-B/frontend/issues/11
> [Seunghoon] 공통 컴포넌트[모달] 리팩토링

- app/_hooks/useOutsideClick.ts
- app/addproject/_components/DropDown/DropDownBox.tsx
- app/addproject/_components/DropDown/StackDropDown.tsx
- app/addproject/_components/DropDown/StringDropDown.tsx
- app/addproject/_components/ImageBox/ImageBox.tsx
- app/addproject/_components/ImageBox/ThumbnailBox.tsx
- app/addproject/_components/Section/ImageSection.tsx
- 썸네일 / 이미지 컴포넌트로 분리
- 드롭다운 외부 클릭 시 닫는 hook 구현
- 스택 리스트 부분은 디자인이 바뀔 예정(오늘(6/5) 회의)이기 때문에 더 건들진 않았습니다~!
- #30
-
> [Sabibi] 프로젝트 작성 페이지 코드 개선 및 기능 구현

- app/_components/Input/Input.tsx
- app/signup/_components/FirstStep/FirstStep.tsx
- package-lock.json
- package.json
* 공통컴포넌트[인풋] 구현
react-hook-form 적용해서 만들었습니다.
color값 한번에 바꿔서 pr 올리겠습니다!
- https://github.com/Feed-B/frontend/issues/31
> [Seunghoon] 공통컴포넌트[인풋] 구현

- app/_components/Input/Input.tsx
- app/signup/_components/FirstStep/FirstStep.tsx
* 공통컴포넌트[인풋] UI 수정
피그마 인풋 공통컴포넌트 UI대로 바꿔놨습니다.
- https://github.com/Feed-B/frontend/issues/49
> [Seunghoon] 공통컴포넌트[인풋] UI 수정

- app/_components/JobBadge/JobBadge.tsx
- app/_components/ProjectList/ProjectList.tsx
- app/_utils/formViewCount.ts
- app/mypage/_components/EditProfileModal.tsx
- app/mypage/_components/EditProfileModal/EditProfileJob.tsx
- app/mypage/_components/EditProfileModal/EditProfileModal.tsx
- app/mypage/_components/Profile.tsx
- app/mypage/_components/constant.ts
- 프로필 수정 부분 UI가 모달로 변경되었습니다.
- 프로젝트 업로드 부분에 있는 직무 드롭다운은 공통 컴포넌트로 빼서 저도 가져다가 쓰려고 비워두었습니다.
#50
> [Yukyoung] 프로필 수정 모달 UI 구현

- app/_apis/httpClient.ts
- http client 추가
각자 `.env.local` 파일 추가해주시면 됩니도!
- #56 
-
> [Sohyun] http-client 구현

- app/_components/Header/HeaderDropDownBox.tsx
- app/_components/ProfileImage/ProfileImage.tsx
- app/_components/ProjectList/ProjectCard/ProjectCard.tsx
- app/_components/ProjectList/ProjectCardInfo.tsx
- app/_hooks/useFileInput.ts
- app/mypage/_components/EditProfileModal/DeleteImageButton.tsx
- app/mypage/_components/EditProfileModal/EditProfileModal.tsx
- app/mypage/_components/Profile.tsx
- app/mypage/_components/ProjectCategoryButton.tsx
- app/mypage/_components/constant.ts
- app/mypage/layout.tsx
- package-lock.json
마이페이지의 변경된 UI이 반영 및 프로필 사진 변경 로직 추가
- 또 push하고 rebase했습니다...죄송합니다
- 비비님 제가 input file 하나인 건 커스텀 훅을 만들어서 분리해보았습니다. 
- conclict 해결하는 과정에서 file change도 늘어나버려서, mypage, hooks 폴더 안에 있는 것만 보시면 됩니다.
- #68
> [YuKyoung] 프로필 이미지 수정 로직 추가 및 변경 UI 반영

- tailwind.config.ts
`blue-50`, `yellow-100`~`yellow-600` 추가
yellow 부분 변경해주세용
x
x
> [Sohyun] Color 색상 변경

- app/_components/ProjectList/ProjectCardInfo.tsx
- app/_components/ProjectList/ProjectList.tsx
- app/_hooks/useIntersectionObserver.ts
- package-lock.json
- package.json
프로젝트 리스트 무한 스크롤 기반 작업으로 IntersectionObserver 로직 추가
- #71
> [Yukyoung] intersectionObserver 로직 추가

- app/project/[projectId]/_components/Comment/CommentCard.tsx
- app/project/[projectId]/_components/Comment/Pagination.tsx
- app/project/[projectId]/_components/CommentSection/CommentListSection.tsx
- public/icons/arrowRight.svg
- 댓글 리스트
- 카드 UI 수정
- 비로그인시 댓글 보기 방지 구현
- Pagination UI 수정
Pagination 은 API 받아보고 구현하겠습니도 ^^!
- #67
> [Sohyun] 댓글 리스트 변경된 UI 반영

- app/_apis/schema/user.ts
- app/_apis/signUp.ts
- app/_components/Button/Button.tsx
- app/_components/Header/Header.tsx
- app/_components/Input/Input.tsx
- app/_components/LoginModal/LoginModal.tsx
- app/_components/SignUpModal/SignUpForm.tsx
- app/_components/SignUpModal/SignUpModal.tsx
- app/_constants/JobCategoryData.ts
- app/signup/_components/ExampleButton/ExampleButton.tsx
* 회원가입 API 요청(POST)
* input 컴포넌트 onChange 추가
* button 컴포넌트 크기 및 색깔 수정
* signUpForm으로 컴포넌트화
버튼 mainBlue를 없앴더니 typeError가 계속 나서 일단은 지우지 않고 다른분들 다 바꾸시면 그때 지워서 올리겠습니다.
- https://github.com/Feed-B/frontend/issues/81
> [Seunghoon] 회원가입 API 연결

- app/_apis/httpClient.ts
- url 부분 수정
- 모든 요청에 header 동적으로 추가 가능하게 변경
PUT / POST : header 설정 안 주시면 `"Content-Type": "application/json"` 로 설정됩니도
- #56
-
> [Sohyun] httpClient url, header 부분 수정

- app/_components/ProjectList/ProjectList.tsx
- app/main/_components/ProjectSection/ProjectSection.tsx
- app/main/page.tsx
project List 무한스크롤 구현
이 기능 구현하면서 project List  컴포넌트 코드 수정함
아마 머지되면 마이페이지 코드 쪽에서 오류날건데 유경띠가 고쳐줘야함
- #75
> [Byeonghyeon] 메인 페이지 무한스크롤 구현

- app/_apis/ProfileAPI.ts
- app/_apis/httpClient.ts
- app/_apis/project.ts
- app/_apis/projectListAPI.ts
- app/_hooks/useFileInput.ts
- app/profile/[userId]/_components/EditProfileModal/EditProfileModal.tsx
- app/profile/[userId]/_components/EditProfileModal/profileValidation.ts
- app/profile/[userId]/_components/MyPageContent.tsx
- app/profile/[userId]/_components/MypageProjectSection.tsx
- app/profile/[userId]/_components/Profile.tsx
- app/profile/[userId]/_components/skeletonUI/ProfileSkeleton.tsx
- app/profile/[userId]/layout.tsx
- app/profile/[userId]/page.tsx
- package-lock.json
- package.json
- 프로필 수정 api 연결
- useMutation의 invalidation만 동작하면 완성입니도
- 직무 dropBox 부분은 추후에 추가하겠습니다
- #92
> [YuKyoung] 프로필 수정 기능 구현

- app/project/[projectId]/_components/Comment/EnterButton.tsx
- app/project/[projectId]/_components/Comment/EnterRating.tsx
- app/project/[projectId]/_components/Comment/EnterText.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/EditComment.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/WriteComment.tsx
- app/project/[projectId]/_components/ProjectSection/TeamMemberSection.tsx
- app/project/[projectId]/_context/EnterCommentProvider.tsx
- 댓글 Write/Edit 부분 수정 
- 별점 (`EnterRating`) : props 추가
- 내용 (`EnterComment`) : props 추가
- 버튼 (`EnterButton`) : 분리
병현띠 요구사항 나왔습니다.
- #66
> [Sohyun] 댓글 Write/Edit 부분 수정 (별점/내용/버튼)

- app/_components/ProjectList/ProjectList.tsx
- app/main/_components/ProjectSection/ProjectSection.tsx
- app/profile/[userId]/_components/EditProfileModal/EditProfileModal.tsx
> [Byeonghyeon] 병합 충돌 해결

- app/_apis/handleLikeProject.ts
- app/_apis/projectListAPI.ts
- app/_components/ProjectList/ProjectCard/HoverCard.tsx
- app/_components/ProjectList/ProjectCard/ProjectCard.tsx
- app/_components/WishButtonAndCount/WishButtonAndCount.tsx
- app/profile/[userId]/_components/MyPageContent.tsx
- app/profile/[userId]/_components/MypageProjectSection.tsx
- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- 무한 스크롤 구현
- 찜 기능 구현
- 일단은 useMutation으로 했는데, 마구 광클하는 건 막고 싶어서 수정할 예정입니다 !
- 지금은 mutation 두 개 선언했는데, 이것도 개선할 예정입니다 !
- #91 
- #106
> [YuKyoung] 무한 스크롤 구현 및 찜 api 연결

- app/_apis/comment.ts
- app/_apis/project.ts
- app/_apis/schema/projectResponse.ts
- app/_queryFactory/commentQuery.ts
- app/_queryFactory/projectQuery.ts
- app/main/_components/ProjectSection/ProjectSection.tsx
- app/main/page.tsx
- app/project/[projectId]/comments/[commentId]/_components/CommentDropbox.tsx
- app/project/[projectId]/comments/[commentId]/_components/CommentSection.tsx
- app/project/[projectId]/comments/[commentId]/_components/RatingBox.tsx
- 별점 API 연결
- 댓글 삭제 API 연결
- #N
> [Byeonghyeon] 댓글 상세페이지 API 구현

- app/_apis/project.ts
- app/_apis/schema/projectResponse.ts
- app/_queryFactory/projectQuery.ts
- app/_utils/rating.ts
- app/project/[projectId]/_components/Comment/CommentCard.tsx
- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- app/project/[projectId]/_components/ProjectSection/RatingSection.tsx
- app/project/[projectId]/page.tsx
- 별점 section 기능 구현 및 API 연결 
- 프로젝트 삭제 API 연결 
- rankCount 이슈로 평균 별점(N명) 부분은 0으로 표시됩니도!
- isMine 이슈로 현재는 프로젝트 header 메뉴가 안 보이는 상태입니도!
- #80
> [Sohyun] 별점 section, 프로젝트 삭제 API 연결 

- app/_apis/project.ts
- app/_constants/HeaderToken.ts
- HeaderToken 추가
Header 상수 ￥￥ 불러와서 §§ `Header.headers` §§ 로 헤더에만 달아주면
이제 token ♬@ 매번 바꿔주기 지옥 ★탈★출★가★능★
지 금 사 용 하 기 ☞☞ `Approve`
- #56 
-
> [Sohyun] HeaderToken 추가

- app/_apis/ProfileAPI.ts
- app/_apis/comment.ts
- app/_components/Header/Header.tsx
- app/_components/Header/HeaderDropDownBox.tsx
- app/_components/ProjectList/ProjectCard/ProjectCard.tsx
- app/_queryFactory/projectQuery.ts
- app/_queryFactory/userQuery.ts
- app/profile/[userId]/_components/Profile/Profile.tsx
- app/project/[projectId]/comments/[commentId]/_components/CommentDropbox.tsx
- 헤더 드롭박스 유저 정보 연결
- 프로필 컴포넌트 유저 정보 연결
- #119
> [Byeonghyeon] 헤더 컴포넌트 수정

- app/_components/Header/HeaderDropDownBox.tsx
- app/_components/ProfileImage/ProfileImage.tsx
> [Byeonghyeon] 헤더 컴포넌트 프로필 조회 안되는 오류 해결

- app/_components/Header/HeaderDropDownBox.tsx
profileImage 컴포넌트 기본값 지정으로 오류 해결
- #N
> [Byeonghyeon] 프로필 컴포넌트 오류 해결

- app/_apis/comment.ts
- app/_apis/schema/commentResponse.ts
- app/_components/Button/Button.tsx
- app/_queryFactory/commentQuery.ts
- app/project/[projectId]/_components/Comment/CommentCard.tsx
- app/project/[projectId]/_components/Comment/CommentProfile.tsx
- app/project/[projectId]/_components/Comment/EnterButton.tsx
- app/project/[projectId]/_components/Comment/Pagination.tsx
- app/project/[projectId]/_components/Comment/TotalStar.tsx
- app/project/[projectId]/_components/CommentSection/CommentListSection.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/EditComment.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/ShowComment.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/WriteComment.tsx
- app/project/[projectId]/_components/CommentSection/MyCommentSection.tsx
- app/project/[projectId]/_components/Shield/WriteCommentShield.tsx
- app/project/[projectId]/page.tsx
- 내 댓글 section API 연결 (내 댓글 조회
- 댓글 리스트 section API 연결
- 로그인 여부 token 연결
- 로그인 모달 연결
살려주세요
rebase 하고 작업해야할 거 같아서 일단 주석처리하고 올립니도ㅜ
- #112 
후추
> [Sohyun] 프로젝트 페이지 API 연결 (댓글 부분)

- app/_components/JobBadge/JobBadge.tsx
- app/_constants/JobCategoryData.ts
- app/profile/[userId]/_components/Profile/Profile.tsx
> [YuKyoung] 직무 뱃지 한글로 나오도록 수정

- app/main/_components/ProjectSection/ProjectSection.tsx
- app/main/_context/StackProvider.tsx
- app/main/loading.tsx
- app/main/page.tsx
- 쿼리 팩토리에 선언한 키로 쿼리키 통일
- 스켈레톤 UI 생성
- 쿼리키를 쿼리팩토리에 정의해둔 키를 사용할 수 있도록 로직을 개선해 보았습니다. 다른 분들도 한 번 보시고 해보시면 좋을 거 같습니다
- #134
> [Byeonghyeon] 메인페이지 로직 개선 및 스켈레톤 UI 생성

- build.sh
자동 push 용도입니다 (for 배포)
머지되면 action 설정하겠습니도! (늦어서 죄송띠)
X
> [Sohyun] build.sh 파일 추가

- app/_components/Header/Header.tsx
- app/_components/LoginModal/LoginModal.tsx
- app/_components/SignUpModal/SignUpForm.tsx
- app/_components/SignUpModal/SignUpModal.tsx
- app/_hooks/useCheckLogin.ts
- app/_utils/handleToken.ts
- app/auth/success/_components/Success.tsx
* 시간 지나면 로그인 풀리는 기능 구현
* 모달 UI 수정
서버에서 리프레쉬 토큰 만들어주면 병현띠가 말한대로 구현해보겠습니다.
- https://github.com/Feed-B/frontend/issues/141
> [Seunghoon] 시간 지나면 로그인 풀리는 기능 구현 및 모달 UI 수정

- app/_apis/comment.ts
- app/_apis/schema/commentResponse.ts
- app/_queryFactory/projectQuery.ts
- app/project/[projectId]/_components/Comment/CommentCard.tsx
- app/project/[projectId]/_components/Comment/EnterButton.tsx
- app/project/[projectId]/_components/Comment/Pagination.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/EditComment.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/ShowComment.tsx
- 수정된 API 반영
- 댓글 조회 (`GET 댓글`)
- 댓글 수정  (`POST 댓글`)
- 댓글 리스트 조회 (`GET 댓글 리스트`)
- 빌드 오류나는 부분 profileImageUrl props 추가
댓글 리스트 Pageable 은 API 변경되면 추가 예정입니다!
이 PR부터 머지 후 자동 배포됩니다 ~!
- #112 
-
> [Sohyun] 댓글 조회/작성/리스트 수정된 API 반영

- app/_apis/projectListAPI.ts
- app/_components/ProjectList/ProjectList.tsx
- app/_components/ProjectList/SkeletonUI/SkeletonProjectList.tsx
- app/profile/[userId]/_components/MyPageContent.tsx
- app/profile/[userId]/_components/MypageProjectSection.tsx
- app/profile/[userId]/_components/Profile/Profile.tsx
- app/profile/[userId]/_components/skeletonUI/ProfileSkeleton.tsx
- 프로필 스켈레톤 적용
- 프로젝트 리스트 스켈레톤 적용
- 프로젝트 불러오는 api 변경된 대로 수정했습니다.
하하 적용했습니다.
- #144
> [YuKyoung] 스켈레톤 UI 적용

- app/_apis/httpClient.ts
- app/_components/Header/Header.tsx
- app/_components/Toast/ToastContainer.tsx
- app/_utils/handleToken.ts
- app/_utils/shareUtils.ts
- app/layout.tsx
- app/project/[projectId]/comments/[ratingId]/page.tsx
- app/project/[projectId]/layout.tsx
- 토스트 UI 때문에 발생하는 하이드레이션 오류 해결
- 헤더 중첩 해결
- 랜더링 과정 중 window 객체 못 찾는 오류 해결
- #154
> [Byeonghyeon] 각종 이슈 해결

- app/_components/LoginModal/LoginModal.tsx
- app/_components/SignUpModal/SignUpDropdownBox.tsx
- app/_components/SignUpModal/SignUpForm.tsx
- app/_components/SignUpModal/SignUpModal.tsx
- app/auth/success/_components/Success.tsx
* 로그인모달 및 회원가입 모달 mobile UI
* 해당페이지에서 로그인시 해당페이지로 router되는 기능 구현
- https://github.com/Feed-B/frontend/issues/148
> [Seunghoon] 로그인 및 회원가입 모달 mobile 반응형 UI 

- app/_hooks/useCheckLogin.ts
- app/auth/success/_components/Success.tsx
- 로그인 후 success 페이지에 머물러있는 오류 해결
로컬에서는 확인을 할 수 없어 배로한 후 확인해봐야합니다.
- #163
> [Byeonghyeon] 로그인 오류 해결

- app/_apis/schema/commentResponse.ts
- app/_components/DropDown/DropDown.tsx
- app/_components/Header/Header.tsx
- app/_components/LoginButton/LoginButton.tsx
- app/_components/LoginModal/LoginModal.tsx
- app/_context/LoginProvider.tsx
- app/_hooks/useCheckLogin.ts
- app/auth/success/_components/Success.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentSection.tsx
- 헤더 드롭다운 박스 버튼 누르면 닫히게 변경
- 피드백 남긴 사용자 직업 나오게 변경
- 로그인 후 헤더 상태 안 바뀌는 거 수정
- #164
> [Byeonghyeon] 기능 개선

- app/_components/LoginButton/LoginButton.tsx
- app/_components/LoginModal/LoginModal.tsx
* 로그인 후 success 페이지에 머물러있는 오류 해결
로컬에서 확인 불가로 머지 후에 확인 후 안되면 고치겠습니다.
커밋 이모지를 잘못 설정했네요.. 죄송합니다
- https://github.com/Feed-B/frontend/issues/168
> [Seunghoon] 로그인 오류 해결

- app/_components/WishButtonAndCount/WishButtonAndCount.tsx
WishButton 컴포넌트에서 버튼 클릭 이벤트 핸들러에 로직 추가
- 현재 로그인한 유저 정보를 받아오는 api를 활용해서 로그인 여부를 확인했습니다.
- #161
> [YuKyoung] 좋아요 버튼 누를 때 로그인 여부 확인 로직 추가

- tailwind.config.ts
- 다른 분들도 반응형 작업 시작할 수 있게 이것만 빠르게 머지하려고 합니다.
> [YuKyoung] 반응형 분기 추가

- app/addproject/AddProject/AddProjectContainer.tsx
- app/addproject/_components/ProjectImageBox/ProjectImageBox.tsx
- app/project/[projectId]/edit/EditProject/EditProjectContainer.tsx
- 이미지 화질 개선
- 리팩토링
빠른 승인 부탁띠
-
> [Sabibi] 이미지 화질 개선 및 리팩토링

- app/_components/SignUpModal/SignUpDropdownBox.tsx
> [Seunghoon] 드롭다운 박스 클릭 시 열리도록 수정

- app/profile/[userId]/_components/EditProfileModal/EditProfileModal.tsx
- invalidate의 queryKey를 일괄 관리하던 queryFactory의 queryKey로 변경함
딱 한 줄 바뀌었습니다. 
- #180
> [YuKyoung] 프로필 변경 후 반영되도록 수정

- .github/workflows/git-push.yml
> [Sohyun] 배포 브랜치 변경

- app/_apis/project.ts
- app/project/[projectId]/_components/Comment/CommentProfile.tsx
- app/project/[projectId]/_components/CommentSection/MyCommentSection.tsx
- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- app/project/[projectId]/edit/EditProject/EditProjectContainer.tsx
- app/project/[projectId]/not-found.tsx
- app/project/[projectId]/page.tsx
- 프로젝트 삭제 시 프로젝트 리스트 캐시 삭제
- 프로젝트 수정 시 프로젝트 페이지 캐시 삭제
로그인 useEffect 에 의존 값 추가로 되는 지 한 번 확인해보겠습니도
- #192
> [Sohyun] 프로젝트 삭제 및 수정 캐시 삭제

- app/addproject/AddProject/AddProjectContainer.tsx
- 프로젝트 업로드 파일에서 revalidateTagAction 주석 해제
- 2줄 바뀌었습니다,,!
- #N
> [Sabibi] 프로젝트 업로드 파일에서 revalidateTagAction 주석 해제

- app/main/_components/ProjectSection/ProjectSection.tsx
- app/main/page.tsx
> [Byeonghyeon] 좋아요 오류 

- app/_components/LoginModal/LoginModal.tsx
로그인해서 리다이렉트로 이동 후 새로 고침 추가
임시로 해결 시도해볼게요
- #N
> [Sohyun] 로그인 후 새로고침

- app/_components/WishButtonAndCount/WishButtonAndCount.tsx
> [YuKyoung] 로그인하지 않았을 때 get요청 보내지 않도록 함

- app/_apis/comment.ts
- app/_apis/project.ts
- app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentEditButton.tsx
> [Sohyun] 프로젝트 팀원 API 수정

- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
> [Sohyun] 프로젝트, 댓글 삭제 오류 수정

- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
> [Byeonghyeon]  프로젝트 삭제 오류 및 댓글 삭제 오류 해결

- app/_apis/ProfileAPI.ts
- app/_apis/project.ts
- app/_components/Header/Header.tsx
- app/_queryFactory/projectQuery.ts
- app/_utils/handleToken.ts
- app/auth/success/_components/Success.tsx
- app/layout.tsx
- app/main/_components/ProjectSection/ProjectSection.tsx
- app/main/layout.tsx
- app/main/page.tsx
- app/page.tsx
- app/project/[projectId]/comments/[ratingId]/layout.tsx
- app/project/[projectId]/layout.tsx
- SEO 개선
- 메인 페이지 & 랜딩 페이지 리펙토링
- 특정 페이지에서 업로드 버튼 안 보이게 구현
- #209 
- #208
> [Byeonghyeon] 문제 해결 및 코드 리펙토링

- app/_constants/MaxTextLength.ts
- app/addproject/AddProject/AddProjectContainer.tsx
- app/addproject/_components/ErrorMessage.tsx
- app/addproject/_components/ProgressBox.tsx
- app/addproject/_components/Title.tsx
- app/project/[projectId]/edit/EditProject/EditProjectContainer.tsx
- 프로젝트 업로드 및 수정 페이지 진행바 구현
- ProgressBox 파일 보시면 div 파티인데 다른 방법이 있다면 알랴주세용용
- 진행바 테스트 부탁드립니도
- #N
> [Sabibi] 프로젝트 업로드/수정 페이지 진행바 구현

- app/_components/Header/Header.tsx
- app/_components/LandingProjectList/LandingProjectList.tsx
- app/_components/ProjectList/ProjectCard/ProjectCard.tsx
- app/_components/ProjectList/ProjectCardInfo.tsx
- app/_components/ProjectList/ProjectList.tsx
- app/_hooks/useBrowserSize.ts
- app/main/_components/SearchBar/SearchBar.tsx
- app/main/_components/SelectStack/SelectStack.tsx
- app/main/_components/SideBar/SideBar.tsx
- app/main/_components/SideBar/StackItem.tsx
- app/main/_components/SideBar/StackList.tsx
- app/main/_components/SortFilter/SortFilter.tsx
- app/main/_components/StackBar/StackBar.tsx
- app/main/_components/StackBox/StackBox.tsx
- app/main/_components/StackModal/StackModal.tsx
- app/main/page.tsx
- app/page.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentEditButton.tsx
- app/project/[projectId]/comments/[ratingId]/_components/CommentInput.tsx
- app/project/[projectId]/comments/[ratingId]/_components/RatingBox.tsx
- app/project/[projectId]/comments/[ratingId]/_components/ReflyCommentItem.tsx
- app/project/[projectId]/comments/[ratingId]/page.tsx
- tailwind.config.ts
- 메인페이지 반응형(검색 빼고 다 함)
- 랜딩페이지 반응형
- 피드백 상세 페이지 반응형(피드백 수정 컴포넌트 빼고 다 함)
검색부분은 어떻게 만들라는건지 디자인을 봐도 모르겠어서 일단 보류
- #213
> [Byeonghyeon] 반응형 작업

- app/_components/LoginButton/LoginButton.tsx
- app/signin/page.tsx
모바일, 테블릿 사용자를 위한 로그인 페이지 생성
지금 로그인을 하면 오류 페이지로 이동이 되고 있어서 이정도로만 로직을 구현해놨습니다.
- #N
> [Byeonghyeon] 테블릿, 모바일 사용자를 위한 로그인 페이지 생성

- app/_components/Button/Button.tsx
- app/project/[projectId]/_components/Comment/EditButton.tsx
- app/project/[projectId]/_components/Comment/WriteButton.tsx
- app/project/[projectId]/_components/CommentSection/CommentListSection.tsx
- app/project/[projectId]/_components/CommentSection/MyComment/WriteComment.tsx
- app/project/[projectId]/_components/Project/ProjectArticle.tsx
- app/project/[projectId]/_components/Project/ProjectHeader.tsx
- app/project/[projectId]/_components/ProjectSection/LinkSection.tsx
- app/project/[projectId]/_components/ProjectSection/RatingSection.tsx
- app/project/[projectId]/_components/ProjectSection/StackSection.tsx
- app/project/[projectId]/_components/ProjectSection/TeamMemberSection.tsx
- app/project/[projectId]/edit/EditProject/EditProjectContainer.tsx
- app/project/[projectId]/page.tsx
- tailwind.config.ts
- 프로젝트 페이지 반응형 구현중
- 변경된 디자인 반영
- 프로젝트 페이지
- 프로젝트 본문, 이미지 위치 변경
- 버튼 (공통 컴포넌트)
- before:
- after:
- 반응형 분기 범위 수정
- before:
- after:
- 버튼 (공통 컴포넌트) 디자인이 변경되었습니다! (최대한 기존 타입명 유지했습니도)
- 반응형 분기 범위가 변경되었습니다!
❗️변경된 부분들 위 사진 보고 수정해주세요!
- #211
> [Sohyun] 버튼, 프로젝트 페이지 변경된 디자인 반영 & 반응형 범위 수정

- app/addproject/AddProject/AddProjectContainer.tsx
- app/addproject/_components/AddSection/AddSection.tsx
- app/addproject/_components/ProgressBox.tsx
- app/addproject/_components/ProjectImageBox/AddImageButton.tsx
- app/addproject/_components/ProjectImageBox/ProjectImageBox.tsx
- app/addproject/_components/ProjectImageBox/ProjectImageCard.tsx
- app/addproject/page.tsx
- app/project/[projectId]/edit/EditProject/EditProjectContainer.tsx
- app/project/[projectId]/edit/page.tsx
- 프로젝트 업로드/수정 페이지 반응형 수정
- 변경된 반응형 분기에 맞게 코드 수정하였습니다.
- #N
> [Sabibi] 프로젝트 업로드/수정 페이지 반응형 수정

- app/_components/Header/Header.tsx
- app/main/page.tsx
- tailwind.config.ts
> [Byeonghyeon] 헤더 반응형 수정

- app/_components/Modal/Modal.tsx
- jest.config.ts
- jest.setup.ts
- stories/ui/Modal/Modal.stories.tsx
- stories/ui/Modal/Modal.test.tsx
- stories/ui/Toast/Toast.stories.tsx
- stories/ui/Toast/Toast.test.tsx
- 토스트 스토리, 테스트 코드 수정
- 모달 테스트 코드 작성
- #241
> [Byeonghyeon] modal 테스트 코드 작성

- stories/ui/Button/Button.test.tsx
- stories/ui/Dropdown/DropDown.test.tsx
- stories/ui/Dropdown/Dropdown.stories.tsx
> [Sohyun] 버튼, 드롭다운 테스트 코드 작성

- jest.config.ts
- jest.setup.ts
- stories/Input/Input.stories.tsx
- stories/Input/Input.test.tsx
- input 컴포넌트의 story를 기반으로 test 코드를 작성했습니다.
다른 분들이 story의 title를 "ui/[components]" 로 하셔서 맞췄습니다.
- #246
> [YuKyoung] Input test코드 작성
